use crate::re::form_enum_string::FormEnumString;
use core::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u32)]
pub enum FormType {
    None = 0,
    PluginInfo = 1,
    FormGroup = 2,
    GameSetting = 3,
    Keyword = 4,
    LocationRefType = 5,
    Action = 6,
    TextureSet = 7,
    MenuIcon = 8,
    Global = 9,
    Class = 10,
    Faction = 11,
    HeadPart = 12,
    Eyes = 13,
    Race = 14,
    Sound = 15,
    AcousticSpace = 16,
    Skill = 17,
    MagicEffect = 18,
    Script = 19,
    LandTexture = 20,
    Enchantment = 21,
    Spell = 22,
    Scroll = 23,
    Activator = 24,
    TalkingActivator = 25,
    Armor = 26,
    Book = 27,
    Container = 28,
    Door = 29,
    Ingredient = 30,
    Light = 31,
    Misc = 32,
    Apparatus = 33,
    Static = 34,
    StaticCollection = 35,
    MovableStatic = 36,
    Grass = 37,
    Tree = 38,
    Flora = 39,
    Furniture = 40,
    Weapon = 41,
    Ammo = 42,
    NPC = 43,
    LeveledNPC = 44,
    KeyMaster = 45,
    AlchemyItem = 46,
    IdleMarker = 47,
    Note = 48,
    ConstructibleObject = 49,
    Projectile = 50,
    Hazard = 51,
    SoulGem = 52,
    LeveledItem = 53,
    Weather = 54,
    Climate = 55,
    ShaderParticleGeometryData = 56,
    ReferenceEffect = 57,
    Region = 58,
    Navigation = 59,
    Cell = 60,
    Reference = 61,
    ActorCharacter = 62,
    ProjectileMissile = 63,
    ProjectileArrow = 64,
    ProjectileGrenade = 65,
    ProjectileBeam = 66,
    ProjectileFlame = 67,
    ProjectileCone = 68,
    ProjectileBarrier = 69,
    PlacedHazard = 70,
    WorldSpace = 71,
    Land = 72,
    NavMesh = 73,
    TLOD = 74,
    Dialogue = 75,
    Info = 76,
    Quest = 77,
    Idle = 78,
    Package = 79,
    CombatStyle = 80,
    LoadScreen = 81,
    LeveledSpell = 82,
    AnimatedObject = 83,
    Water = 84,
    EffectShader = 85,
    TOFT = 86,
    Explosion = 87,
    Debris = 88,
    ImageSpace = 89,
    ImageAdapter = 90,
    FormList = 91,
    Perk = 92,
    BodyPartData = 93,
    AddonNode = 94,
    ActorValueInfo = 95,
    CameraShot = 96,
    CameraPath = 97,
    VoiceType = 98,
    MaterialType = 99,
    Impact = 100,
    ImpactDataSet = 101,
    Armature = 102,
    EncounterZone = 103,
    Location = 104,
    Message = 105,
    Ragdoll = 106,
    DefaultObject = 107,
    LightingMaster = 108,
    MusicType = 109,
    Footstep = 110,
    FootstepSet = 111,
    StoryManagerBranchNode = 112,
    StoryManagerQuestNode = 113,
    StoryManagerEventNode = 114,
    DialogueBranch = 115,
    MusicTrack = 116,
    DialogueView = 117,
    WordOfPower = 118,
    Shout = 119,
    EquipSlot = 120,
    Relationship = 121,
    Scene = 122,
    AssociationType = 123,
    Outfit = 124,
    ArtObject = 125,
    MaterialObject = 126,
    MovementType = 127,
    SoundRecord = 128,
    DualCastData = 129,
    SoundCategory = 130,
    SoundOutputModel = 131,
    CollisionLayer = 132,
    ColorForm = 133,
    ReverbParam = 134,
    LensFlare = 135,
    LensSprite = 136,
    VolumetricLighting = 137,
    Max = 138,
}

impl FormType {
    pub const fn as_str(&self) -> &'static str {
        match self {
            FormType::PluginInfo => "TES4",
            FormType::FormGroup => "GRUP",
            FormType::GameSetting => "GMST",
            FormType::Keyword => "KYWD",
            FormType::LocationRefType => "LCRT",
            FormType::Action => "AACT",
            FormType::TextureSet => "TXST",
            FormType::MenuIcon => "MICN",
            FormType::Global => "GLOB",
            FormType::Class => "CLAS",
            FormType::Faction => "FACT",
            FormType::HeadPart => "HDPT",
            FormType::Eyes => "EYES",
            FormType::Race => "RACE",
            FormType::Sound => "SOUN",
            FormType::AcousticSpace => "ASPC",
            FormType::Skill => "SKIL",
            FormType::MagicEffect => "MGEF",
            FormType::Script => "SCPT",
            FormType::LandTexture => "LTEX",
            FormType::Enchantment => "ENCH",
            FormType::Spell => "SPEL",
            FormType::Scroll => "SCRL",
            FormType::Activator => "ACTI",
            FormType::TalkingActivator => "TACT",
            FormType::Armor => "ARMO",
            FormType::Book => "BOOK",
            FormType::Container => "CONT",
            FormType::Door => "DOOR",
            FormType::Ingredient => "INGR",
            FormType::Light => "LIGH",
            FormType::Misc => "MISC",
            FormType::Apparatus => "APPA",
            FormType::Static => "STAT",
            FormType::StaticCollection => "SCOL",
            FormType::MovableStatic => "MSTT",
            FormType::Grass => "GRAS",
            FormType::Tree => "TREE",
            FormType::Flora => "FLOR",
            FormType::Furniture => "FURN",
            FormType::Weapon => "WEAP",
            FormType::Ammo => "AMMO",
            FormType::NPC => "NPC_",
            FormType::LeveledNPC => "LVLN",
            FormType::KeyMaster => "KEYM",
            FormType::AlchemyItem => "ALCH",
            FormType::IdleMarker => "IDLM",
            FormType::Note => "NOTE",
            FormType::ConstructibleObject => "COBJ",
            FormType::Projectile => "PROJ",
            FormType::Hazard => "HAZD",
            FormType::SoulGem => "SLGM",
            FormType::LeveledItem => "LVLI",
            FormType::Weather => "WTHR",
            FormType::Climate => "CLMT",
            FormType::ShaderParticleGeometryData => "SPGD",
            FormType::ReferenceEffect => "RFCT",
            FormType::Region => "REGN",
            FormType::Navigation => "NAVI",
            FormType::Cell => "CELL",
            FormType::Reference => "REFR",
            FormType::ActorCharacter => "ACHR",
            FormType::ProjectileMissile => "PMIS",
            FormType::ProjectileArrow => "PARW",
            FormType::ProjectileGrenade => "PGRE",
            FormType::ProjectileBeam => "PBEA",
            FormType::ProjectileFlame => "PFLA",
            FormType::ProjectileCone => "PCON",
            FormType::ProjectileBarrier => "PBAR",
            FormType::PlacedHazard => "PHZD",
            FormType::WorldSpace => "WRLD",
            FormType::Land => "LAND",
            FormType::NavMesh => "NAVM",
            FormType::TLOD => "TLOD",
            FormType::Dialogue => "DIAL",
            FormType::Info => "INFO",
            FormType::Quest => "QUST",
            FormType::Idle => "IDLE",
            FormType::Package => "PACK",
            FormType::CombatStyle => "CSTY",
            FormType::LoadScreen => "LSCR",
            FormType::LeveledSpell => "LVSP",
            FormType::AnimatedObject => "ANIO",
            FormType::Water => "WATR",
            FormType::EffectShader => "EFSH",
            FormType::TOFT => "TOFT",
            FormType::Explosion => "EXPL",
            FormType::Debris => "DEBR",
            FormType::ImageSpace => "IMGS",
            FormType::ImageAdapter => "IMAD",
            FormType::FormList => "FLST",
            FormType::Perk => "PERK",
            FormType::BodyPartData => "BPTD",
            FormType::AddonNode => "ADDN",
            FormType::ActorValueInfo => "AVIF",
            FormType::CameraShot => "CAMS",
            FormType::CameraPath => "CPTH",
            FormType::VoiceType => "VTYP",
            FormType::MaterialType => "MATT",
            FormType::Impact => "IPCT",
            FormType::ImpactDataSet => "IPDS",
            FormType::Armature => "ARMA",
            FormType::EncounterZone => "ECZN",
            FormType::Location => "LCTN",
            FormType::Message => "MESG",
            FormType::Ragdoll => "RGDL",
            FormType::DefaultObject => "DOBJ",
            FormType::LightingMaster => "LGTM",
            FormType::MusicType => "MUSC",
            FormType::Footstep => "FSTP",
            FormType::FootstepSet => "FSTS",
            FormType::StoryManagerBranchNode => "SMBN",
            FormType::StoryManagerQuestNode => "SMQN",
            FormType::StoryManagerEventNode => "SMEN",
            FormType::DialogueBranch => "DLBR",
            FormType::MusicTrack => "MUST",
            FormType::DialogueView => "DLVW",
            FormType::WordOfPower => "WOOP",
            FormType::Shout => "SHOU",
            FormType::EquipSlot => "EQUP",
            FormType::Relationship => "RELA",
            FormType::Scene => "SCEN",
            FormType::AssociationType => "ASTP",
            FormType::Outfit => "OTFT",
            FormType::ArtObject => "ARTO",
            FormType::MaterialObject => "MATO",
            FormType::MovementType => "MOVT",
            FormType::SoundRecord => "SNDR",
            FormType::DualCastData => "DUAL",
            FormType::SoundCategory => "SNCT",
            FormType::SoundOutputModel => "SOPM",
            FormType::CollisionLayer => "COLL",
            FormType::ColorForm => "CLFM",
            FormType::ReverbParam => "REVB",
            FormType::LensFlare => "LENS",
            FormType::LensSprite => "LSPR",
            FormType::VolumetricLighting => "VOLI",
            _ => "NONE",
        }
    }

    pub fn from_str(s: &str) -> Self {
        use core::ffi::CStr;

        // РџСЂРѕС…РѕРґРёРј РїРѕ РѕСЂРёРіРёРЅР°Р»СЊРЅРѕР№ С‚Р°Р±Р»РёС†Рµ РЎРєР°Р№СЂРёРјР°
        for entry in FormEnumString::get_all() {
            if entry.form_string.is_null() {
                continue;
            }

            // Р‘РµР·РѕРїР°СЃРЅРѕ РѕР±РѕСЂР°С‡РёРІР°РµРј СѓРєР°Р·Р°С‚РµР»СЊ РІ CStr
            let c_str = unsafe { CStr::from_ptr(entry.form_string) };

            // РЎСЂР°РІРЅРёРІР°РµРј (case-insensitive)
            if let Ok(form_name) = c_str.to_str() {
                if form_name.eq_ignore_ascii_case(s) {
                    return entry.form_type;
                }
            }
        }
        FormType::None
    }
}

impl TryFrom<u8> for FormType {
    type Error = ();

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Self::try_from(value as u32)
    }
}

impl TryFrom<u32> for FormType {
    type Error = ();

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        if value <= Self::VolumetricLighting as u32 {
            Ok(unsafe { core::mem::transmute::<u32, Self>(value) })
        } else {
            Err(())
        }
    }
}

impl fmt::Display for FormType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

core_util::impl_enumset_type!(FormType => u32);
core_util::impl_enumset_type!(FormType => u8);
