/// C++ `RE::QuestEvent`
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum QuestEvent {
    None = -1,
    KillActor = 0,
    AssaultActor = 1,
    ChangeLocation = 2,
    Script = 3,
    ActorDialogue = 4,
    ActorHello = 5,
    ActivateActor = 6,
    PlayerAddItem = 7,
    PlayerRemoveItem = 8,
    CraftItem = 9,
    PickLock = 10,
    Infection = 11,
    Cure = 12,
    NewVoicePower = 13,
    DeadBody = 14,
    SkillIncrease = 15,
    IncreaseLevel = 16,
    ChangeRelationshipRank = 17,
    IntimidateNPC = 18,
    BribeNPC = 19,
    FlatterNPC = 20,
    PlayerGetsFavor = 21,
    PayFine = 22,
    Jail = 23,
    ServedTime = 24,
    EscapeJail = 25,
    Trespass = 26,
    CrimeGold = 27,
    Arrest = 28,
    CastMagic = 29,
}
