from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from _common import LIBSKYRIM_RE, OFFSETS_HEADERS, OFFSETS_RS, REPO_ROOT, read_text, repo_relative


def expected_re_mod() -> str:
    modules = sorted(path.stem for path in LIBSKYRIM_RE.glob("*.rs") if path.name != "mod.rs")
    lines = [
        "//! =============================================================================",
        "//! This file is auto-generated by `scripts/generate_re_mod.py`.",
        "//! Do not edit it manually. Regenerate it instead.",
        "//! =============================================================================",
        "",
    ]
    lines.extend(f"pub mod {module};" for module in modules)
    lines.append("")
    lines.extend(f"pub use {module}::*;" for module in modules)
    lines.append("")
    return "\n".join(lines)


def expected_offsets_rtti(header_name: str) -> str:
    header_text = read_text(OFFSETS_HEADERS / header_name)
    pattern = re.compile(r"constexpr REL::VariantID\s+(\w+)\(([^,]+),\s*([^,]+),\s*([^)]+)\);")
    lines = [
        "// AUTO-GENERATED FILE",
        "#![allow(non_upper_case_globals)]",
        "use crate::relocation::VariantID;",
        "",
    ]
    for name, se, ae, vr in pattern.findall(header_text):
        lines.append(
            f"pub const {name}: VariantID = VariantID::new({se.strip()}, {ae.strip()}, {vr.strip()});"
        )
    lines.append("")
    return "\n".join(lines)


def expected_offsets_vtable() -> str:
    header_text = read_text(OFFSETS_HEADERS / "Offsets_VTABLE.h")
    pattern_array = re.compile(
        r"constexpr std::array<REL::VariantID,\s*(\d+)>\s+(\w+)\s*\{\s*(.*?)\s*\};",
        re.DOTALL,
    )
    pattern_item = re.compile(r"REL::VariantID\(([^,]+),\s*([^,]+),\s*([^)]+)\)")
    lines = [
        "// AUTO-GENERATED FILE",
        "#![allow(non_upper_case_globals)]",
        "use crate::relocation::VariantID;",
        "",
    ]
    for array_size, name, items_str in pattern_array.findall(header_text):
        items = [
            f"VariantID::new({se.strip()}, {ae.strip()}, {vr.strip()})"
            for se, ae, vr in pattern_item.findall(items_str)
        ]
        lines.append(f"pub const {name}: [VariantID; {array_size}] = [")
        if items:
            lines.extend(f"    {item}," for item in items)
        lines.append("];")
        lines.append("")
    return "\n".join(lines)


def compare_generated(path: Path, expected: str, failures: list[str]) -> None:
    actual = read_text(path)
    if normalize_generated(actual) != normalize_generated(expected):
        failures.append(repo_relative(path))


def normalize_generated(text: str) -> str:
    semantic_parts = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("//"):
            continue
        semantic_parts.append(stripped)
    return re.sub(r"\s+", "", "".join(semantic_parts))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check whether generated repo artifacts are stale without mutating them."
    )
    parser.add_argument(
        "--quiet", action="store_true", help="Print only stale paths and use the exit code"
    )
    args = parser.parse_args()

    failures: list[str] = []
    compare_generated(LIBSKYRIM_RE / "mod.rs", expected_re_mod(), failures)
    compare_generated(OFFSETS_RS / "offsets_rtti.rs", expected_offsets_rtti("Offsets_RTTI.h"), failures)
    compare_generated(
        OFFSETS_RS / "offsets_nirtti.rs", expected_offsets_rtti("Offsets_NiRTTI.h"), failures
    )
    compare_generated(OFFSETS_RS / "offsets_vtable.rs", expected_offsets_vtable(), failures)

    expected_offsets_mod = "// AUTO-GENERATED FILE\npub mod offsets_rtti;\npub mod offsets_nirtti;\npub mod offsets_vtable;\n"
    compare_generated(OFFSETS_RS / "mod.rs", expected_offsets_mod, failures)

    if failures:
        if args.quiet:
            for failure in failures:
                print(failure)
        else:
            print("stale generated artifacts detected:")
            for failure in failures:
                print(f"  - {failure}")
            print("regenerate with:")
            print("  - python scripts/generate_re_mod.py")
            print("  - python scripts/generate_offsets.py")
        return 1

    if not args.quiet:
        print("generated artifacts are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
