[package]
name = "libskyrim"
version = "1.1.0"
edition = "2021"

[dependencies]
core-util  = { path = "../core-util"  }
cstd       = { path = "../cstd"     }
bitflags = "2.11.0"
bytemuck = { version = "1.25.0", features = ["derive"] }

[features]
# По умолчанию собираем универсальный плагин для SE и AE
default = ["se", "ae"]

# Доступные флаги компиляции
se = []
ae = []
vr = []

[dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemInformation",
    "Win32_System_Time"
]

[build-dependencies]
xmake = "0.3.3"
